def Dracula():
    base = {
        "background": "#282a36",
        "foreground": "#f8f8f2",
        "current": "#44475a",
        "comment": "#6272a4",
        "cyan": "#8be9fd",
        "green": "#50fa7b",
        "orange": "#ffb86c",
        "pink": "#ff79c6",
        "purple": "#bd93f9",
        "red": "#ff5555",
        "yellow": "#f1fa8c",
    }
    return {
        "background": "#282a36",
        "foreground": "#f8f8f2",
        "current": "#44475a",
        "comment": "#6272a4",
        "cyan": "#8be9fd",
        "green": "#50fa7b",
        "orange": "#ffb86c",
        "pink": "#ff79c6",
        "purple": "#bd93f9",
        "red": "#ff5555",
        "yellow": "#f1fa8c",
        "bar_background_color": base["background"],
        "bar_group_box_active": base["purple"],
        "bar_group_box_inactive": base["comment"],
        "bar_group_box_highlight_color": base["background"],
        "layout_border_focus": base["purple"],
        "layout_border_normal": base["comment"],
    }
